Add support for Macedonian language
kwn/number-to-words pull request #135
Opened 2022-06-29 21:19 UTC by dimegalev

There is a high chance that you don't know the Macedonian language but it's really not that far off other Slavic languages, please have a look at let me know if I need to make any changes.

Cheers

2022-07-18 19:59 UTC, kwn requested changes
Thank you for the contribution. Could you please add some unit tests?

2022-07-18 19:59 UTC, kwn commented on src/Concerns/ManagesNumberTransformers.php
> +        'mk' => Transformer\MacedonianNumberTransformer::class,
Could you please update the README.md file as well?

2022-07-18 19:59 UTC, kwn commented on src/Legacy/Numbers/Words/Locale/Mk.php
> +                self::$digits[-1][$i] =& self::$digits[0][$i];
Same as above.

2022-07-19 11:15 UTC, dimegalev commented
Thank you for your review, I'll have a look at the requested changes and do the changes as soon as I can.

2022-08-02 13:00 UTC, dimegalev commented
@kwn I've made some changes, think I covered everything that was requested. Let me know if there are any other changes that you'd like to see done.

2022-08-04 06:15 UTC, kwn approved these changes
Thank you. It looks fantastic!

2022-08-04 06:15 UTC, merged