Azerbaijani Language
kwn/number-to-words pull request #138
Opened 2022-07-18 06:10 UTC by kongulov

1) Translate fix
2) Currency Test
3) Add Noun Gender Inflector
4) Add Noun Gender Inflector Test

2022-07-18 06:17 UTC, kongulov commented
Helo @kwn 
Can you please check and merge?

2022-07-18 19:47 UTC, kwn requested changes
Thanks. Just a few minor comments added.

2022-07-18 19:47 UTC, kwn commented on src/CurrencyTransformer/AzerbaijaniCurrencyTransformer.php
> +                sprintf('"%s" valyutası "%s" dilində mövcud deyil', $currency, get_class($this))
The exceptions and generic messages should be all in English. Could you please revert it?

2022-07-18 19:47 UTC, kwn commented on tests/Language/Azerbaijani/AzerbaijaniNounGenderInflectorTest.php
> +        $polishInflector = new AzerbaijaniNounGenderInflector();
```suggestion
        $azerbaijaniInflector = new AzerbaijaniNounGenderInflector();
```

2022-07-18 19:47 UTC, kwn commented on tests/Language/Azerbaijani/AzerbaijaniNounGenderInflectorTest.php
> +        $inflected = $polishInflector->inflectNounByNumber($number, self::$nouns[0], self::$nouns[1], self::$nouns[2]);
```suggestion
        $inflected = $azerbaijaniInflector->inflectNounByNumber($number, self::$nouns[0], self::$nouns[1], self::$nouns[2]);
```

2022-07-19 06:26 UTC, kongulov commented
@kwn Thanks. All is ready

2022-07-19 18:22 UTC, merged

2022-07-19 18:26 UTC, kwn commented
Thanks @kongulov. Released in `2.4.3`.