Add Hebrew
kwn/number-to-words pull request #166
Opened 2023-12-17 05:57 UTC by sbc640964

2023-12-28 12:39 UTC, kwn requested changes
Thank you for adding the translator. It's a great and very valuable contribution. Could you please:

1. Fix linter error
2. Add some unit tests
3. Replace docblocks with type hints
4. Translate other currencies into Hebrew

Thank you in advance!

2023-12-28 12:39 UTC, kwn commented on README.md
> +| Hebrew               | he        | +      | +        |
Could you please order the list alphabetically?

2023-12-28 12:39 UTC, kwn commented on src/Concerns/ManagesNumberTransformers.php
> +        'he' => Transformer\HebrewNumberTransformer::class,
Could you please add `he` on the list in the alphabetical order?

2023-12-28 12:39 UTC, kwn commented on src/Concerns/ManagesCurrencyTransformers.php
> +        'he' => Transformer\HebrewCurrencyTransformer::class,
Could you please add he on the list in the alphabetical order?

2023-12-28 12:39 UTC, kwn commented on src/Language/Hebrew/HebrewDictionary.php
> +        'ALL' => [['lek'], ['qindarka']],
Could you please translate other currencies using Hebrew alphabet?

2023-12-28 12:39 UTC, kwn commented on src/Language/Hebrew/HebrewNounGenderInflector.php
> +    /**
Could you please use type hinting instead of docblocks? This library requires min PHP7

2023-12-28 12:39 UTC, kwn commented on src/Language/Hebrew/HebrewTripletTransformer.php
> +     * @param int $number
Could you please replace docblocks with type hints?

2023-12-28 12:39 UTC, kwn commented on src/Language/Hebrew/HebrewTripletTransformer.php
> +    /**
Same here

2023-12-28 12:39 UTC, kwn commented on src/Language/Hebrew/HebrewNounGenderInflector.php
> +            if($number === 2) {
PSR12 error

```suggestion
            if ($number === 2) {
```

2024-04-07 14:20 UTC, Bryce-Colton commented
@kwn : How I can contribute to finalize this PR ?

I tried on #167 , because it is just some test cases to add.

But : 

- I can't push commit on PR (no permission on the kwn repo)
- I can't push commit on the branch (no permission on the forked repo).

So i'm wonder (as a github noob) how to help on PR suggested by others ...

2025-03-29 07:21 UTC, ahmedazizabbassi commented
@Bryce-Colton GitHub follows the [forking workflow](https://www.atlassian.com/git/tutorials/comparing-workflows) by default.

To contribute, follow these steps:
	1.	Fork the repository.
	2.	Add your fork as a remote: `git remote add myorigin {fork_url}`
	3.	Push your working branch: `git push -u myorigin {working_branch}`

**Note**: This assumes you don’t already have a remote named myorigin.

2026-06-21 14:53 UTC, closed without merging